name: Code formatting
on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install .
      - name: print
        run: echo ${{ github.event.pull_request.title }}