name: Code formatting
on: [workflow_dispatch, push]

jobs:
  build:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
           export RP_TOKEN=${{secrets.token}}
           echo $RP_TOKEN
           echo RP_TOKEN
